"""
baselines/baseline_a.py
=======================
Baseline A: Supervised-only training on the labeled set.

No pseudo-labels. No iterative loop. No unlabeled data.
Train YOLO on the labeled split once, evaluate on val2017.

This is the primary comparison point for the paper.
The claim "our method improves over supervised-only" requires this number.

Supports two split schemas (auto-detected from the split JSON):

  Legacy (full COCO, 80 classes):
    - Generated by data/make_splits.py
    - Requires CLI: --coco_label_dir, --val_image_dir, --val_label_dir
    - Defaults to base_model=yolov8m.pt, pretrained=True, num_classes=80

  Filtered (vehicle subset, 5 classes, from-scratch):
    - Generated by data/make_filtered_coco_splits.py
    - All paths come FROM the split JSON (no path CLI args needed)
    - Defaults to base_model=yolov8s.yaml, pretrained=False, num_classes=5
    - class_names read from split (e.g. [bicycle, car, motorcycle, bus, truck])

The two schemas are detected by presence of `image_dir_train` / `class_names`
fields in the split JSON. CLI flags can override defaults in either case.

Protocol (both schemas — Option A asymmetric inner-val):
  Training input:    split.labeled_train_ids       (90% of labeled set)
  Per-run early stop: split.labeled_inner_val_ids  (10% of labeled set)
  Final evaluation:  filtered val (filtered schema) OR full val2017 (legacy)
  Pseudo-labels:     none — Baseline A is supervised-only

Usage (filtered, recommended for current experiment):
  python baselines/baseline_a.py \\
      --split_file data/splits_vehicles/coco_vehicles_fold0_10pct.json \\
      --output_dir outputs/baseline_a/vehicles_fold0_10pct_smoke \\
      --epochs 30 --patience 10 \\
      --device 0

  Filtered schema auto-derives all path/model/class config from split JSON:
    base_model=yolov8s.yaml, pretrained=False, num_classes=5,
    class_names=[bicycle, car, motorcycle, bus, truck]

Usage (legacy COCO, kept for backward compatibility):
  python baselines/baseline_a.py \\
      --split_file data/splits/coco_fold0_10pct.json \\
      --coco_label_dir ~/research/coco/labels/train2017 \\
      --val_image_dir ~/research/coco/images/val2017 \\
      --val_label_dir ~/research/coco/labels/val2017 \\
      --output_dir outputs/baseline_a/fold0_10pct \\
      --epochs 100 --patience 50 \\
      --device 0
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional, Tuple

# Ensure project root is on sys.path
ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import torch

from autolabel.training.trainer import TrainingConfig, YOLOTrainer
from data.make_splits import (
    load_split,
    split_to_labeled_data,
    filtered_split_to_labeled_data,
)
from eval.evaluate import evaluate_checkpoint, save_results


# ── Schema detection ─────────────────────────────────────────────────────────

def is_filtered_split(split: Dict) -> bool:
    """
    True if the split JSON has the filtered-schema fields.

    A split is filtered iff it carries `class_names` AND `image_dir_train`
    (both written only by make_filtered_coco_splits.py). Either alone could
    be a malformed split — both must be present.
    """
    return "class_names" in split and "image_dir_train" in split


# ── Path resolution ──────────────────────────────────────────────────────────

def resolve_paths(split:                 Dict,
                  cli_coco_label_dir:    Optional[str],
                  cli_val_image_dir:     Optional[str],
                  cli_val_label_dir:     Optional[str]
                  ) -> Tuple[Optional[str], str, str, int, Optional[List[str]]]:
    """
    Compute (coco_label_dir, val_image_dir, val_label_dir, num_classes,
    class_names) for the given split, applying schema-specific defaults
    and respecting any CLI overrides.

    Filtered splits derive everything from the split JSON unless the user
    overrides via CLI flags. Legacy splits require all three path flags.

    Returns:
        coco_label_dir: passed to split_to_labeled_data() for legacy splits;
                        unused for filtered splits (returns None).
        val_image_dir:  for evaluate_checkpoint
        val_label_dir:  for evaluate_checkpoint
        num_classes:    80 for legacy, 5 for filtered (or len(class_names))
        class_names:    None for legacy, vehicle list for filtered
    """
    if is_filtered_split(split):
        # Filtered: derive from split JSON, allow CLI override
        val_image_dir = cli_val_image_dir or split.get("image_dir_val")
        val_label_dir = cli_val_label_dir or split.get("label_dir_val")
        if not val_image_dir or not val_label_dir:
            raise ValueError(
                "Filtered split is missing image_dir_val or label_dir_val. "
                "Either regenerate the split with current "
                "make_filtered_coco_splits.py, or pass --val_image_dir and "
                "--val_label_dir explicitly."
            )
        class_names = split["class_names"]
        num_classes = len(class_names)
        return None, val_image_dir, val_label_dir, num_classes, class_names

    # Legacy: all three path flags required
    missing = [n for n, v in [("--coco_label_dir", cli_coco_label_dir),
                               ("--val_image_dir", cli_val_image_dir),
                               ("--val_label_dir", cli_val_label_dir)]
               if not v]
    if missing:
        raise ValueError(
            f"Legacy (non-filtered) split requires {missing}. "
            f"Either pass them, or use a filtered split JSON from "
            f"make_filtered_coco_splits.py."
        )
    return (cli_coco_label_dir, cli_val_image_dir, cli_val_label_dir,
            80, None)


# ── Main runner ──────────────────────────────────────────────────────────────

def run_baseline_a(split_file:      str,
                   output_dir:      str,
                   coco_label_dir:  Optional[str] = None,
                   val_image_dir:   Optional[str] = None,
                   val_label_dir:   Optional[str] = None,
                   epochs:          int   = 100,
                   patience:        int   = 50,
                   optimizer:       str   = "AdamW",
                   lr0:             float = 0.001,
                   batch:           int   = 16,
                   imgsz:           int   = 640,
                   device:          str   = "0",
                   base_model:      Optional[str] = None,
                   pretrained:      Optional[bool] = None,
                   workers:         int   = 8) -> dict:
    """
    Run the supervised-only baseline for one split.

    base_model and pretrained: if None, use schema-aware defaults.
        Filtered schema: base_model="yolov8s.yaml", pretrained=False
        Legacy schema:   base_model="yolov8m.pt",   pretrained=True

    Returns a summary dict with checkpoint path and mAP results.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    # ── Load split ───────────────────────────────────────────────────────────
    print(f"Loading split: {split_file}")
    split = load_split(split_file)
    schema = "filtered" if is_filtered_split(split) else "legacy"
    print(f"  schema={schema}  ratio={split['ratio']:.0%}  fold={split['fold']}  "
          f"n_labeled={split['n_labeled']:,}")
    print(f"  Inner-val protocol: "
          f"train={split['n_labeled_train']:,}, "
          f"inner_val={split['n_labeled_inner_val']:,} "
          f"(val_fraction={split['val_fraction']})")

    # Resolve paths and class config
    (coco_label_dir_resolved, val_image_dir_resolved,
     val_label_dir_resolved, num_classes, class_names) = resolve_paths(
        split, coco_label_dir, val_image_dir, val_label_dir
    )

    # Schema-aware defaults for model and pretrained
    if base_model is None:
        base_model = "yolov8s.yaml" if schema == "filtered" else "yolov8m.pt"
    if pretrained is None:
        pretrained = (schema != "filtered")

    # ── From-scratch consistency guards ──────────────────────────────────────
    # In Ultralytics, YOLO("yolov8s.pt") loads pretrained weights regardless
    # of any pretrained flag. The actual mechanism for from-scratch training
    # is to pass a .yaml file. These guards make any misuse loud rather
    # than silently invalidating the experimental protocol.
    base_model_str = str(base_model)
    if pretrained is False and base_model_str.endswith(".pt"):
        raise ValueError(
            f"pretrained=False but base_model={base_model_str!r} is a .pt "
            f"checkpoint. .pt files load pretrained weights regardless of "
            f"the pretrained flag. For from-scratch training, use a .yaml "
            f"model file (e.g. 'yolov8s.yaml')."
        )
    if schema == "filtered" and not base_model_str.endswith(".yaml"):
        raise ValueError(
            f"Filtered-schema (5-class vehicle) experiment must use a "
            f".yaml model for from-scratch training. Got "
            f"base_model={base_model_str!r}. Use --base_model yolov8s.yaml "
            f"(or yolov8n.yaml / yolov8m.yaml). Pretrained .pt weights "
            f"contaminate the experiment because they were trained on the "
            f"same COCO images we are now using."
        )

    print(f"  num_classes={num_classes}, "
          f"class_names={class_names if class_names else '<80-class default>'}")
    print(f"  base_model={base_model}, pretrained={pretrained}")
    print(f"  eval val_image_dir: {val_image_dir_resolved}")
    print(f"  eval val_label_dir: {val_label_dir_resolved}")

    # ── Adapter ──────────────────────────────────────────────────────────────
    if schema == "filtered":
        labeled_data = filtered_split_to_labeled_data(split)
    else:
        labeled_data = split_to_labeled_data(
            split, label_dir=coco_label_dir_resolved
        )

    if not labeled_data.get("inner_val_image_list"):
        raise RuntimeError(
            "Adapter did not return inner_val_image_list. "
            "Check that this split was generated by current make_splits.py "
            "or make_filtered_coco_splits.py (post Option A patch)."
        )

    # ── Train ────────────────────────────────────────────────────────────────
    cfg = TrainingConfig(
        epochs      = epochs,
        patience    = patience,
        optimizer   = optimizer,
        lr0         = lr0,
        batch       = batch,
        imgsz       = imgsz,
        device      = device,
        workers     = workers,
        pretrained  = pretrained,
        base_model  = base_model,
        output_dir  = str(output_dir / "training"),
        num_classes = num_classes,
        class_names = class_names,
    )

    print(f"Training {base_model} for up to {epochs} epochs "
          f"(patience={patience}, optimizer={optimizer}, lr0={lr0}) on "
          f"{split['n_labeled_train']:,} train + "
          f"{split['n_labeled_inner_val']:,} inner-val images ...")
    trainer    = YOLOTrainer(cfg)
    checkpoint = trainer.train(
        labeled_data  = labeled_data,
        pseudo_labels = [],   # Baseline A: no pseudo-labels
        round_id      = 0,
    )
    print(f"  Checkpoint: {checkpoint}")

    # ── Evaluate ─────────────────────────────────────────────────────────────
    eval_label = "filtered val2017" if schema == "filtered" else "val2017"
    print(f"Evaluating on {eval_label} ...")
    result = evaluate_checkpoint(
        checkpoint    = checkpoint,
        val_image_dir = val_image_dir_resolved,
        val_label_dir = val_label_dir_resolved,
        num_classes   = num_classes,
        class_names   = class_names,
        imgsz         = imgsz,
        batch         = batch,
        device        = device,
        round_id      = 0,
    )
    print(f"  mAP50:    {result.map50:.4f}")
    print(f"  mAP50-95: {result.map50_95:.4f}")
    if result.per_class:
        print(f"  Per-class AP50:")
        for name, ap in result.per_class.items():
            print(f"    {name}: {ap:.4f}")

    # ── Save results ─────────────────────────────────────────────────────────
    eval_file = output_dir / "eval_result.json"
    save_results(
        results     = [result],
        output_file = str(eval_file),
        metadata    = {
            "baseline":            "A_supervised_only",
            "schema":              schema,
            "split_file":          str(split_file),
            "ratio":               split["ratio"],
            "fold":                split["fold"],
            "n_labeled":           split["n_labeled"],
            "n_labeled_train":     split["n_labeled_train"],
            "n_labeled_inner_val": split["n_labeled_inner_val"],
            "val_fraction":        split["val_fraction"],
            "num_classes":         num_classes,
            "class_names":         class_names,
            "base_model":          base_model,
            "pretrained":          pretrained,
            "epochs":              epochs,
            "patience":            patience,
            "optimizer":           optimizer,
            "lr0":                 lr0,
            "created_at":          datetime.now(timezone.utc).isoformat(),
        }
    )

    summary = {
        "baseline":            "A",
        "schema":              schema,
        "ratio":               split["ratio"],
        "fold":                split["fold"],
        "n_labeled":           split["n_labeled"],
        "n_labeled_train":     split["n_labeled_train"],
        "n_labeled_inner_val": split["n_labeled_inner_val"],
        "num_classes":         num_classes,
        "class_names":         class_names,
        "base_model":          base_model,
        "pretrained":          pretrained,
        "epochs":              epochs,
        "patience":            patience,
        "optimizer":           optimizer,
        "lr0":                 lr0,
        "checkpoint":          checkpoint,
        "map50":               result.map50,
        "map50_95":            result.map50_95,
        "per_class":           result.per_class,
        "eval_file":           str(eval_file),
    }

    summary_file = output_dir / "summary.json"
    with open(summary_file, "w") as f:
        json.dump(summary, f, indent=2)
    print(f"Summary saved to {summary_file}")

    return summary


# ── Entry point ───────────────────────────────────────────────────────────────

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Baseline A: supervised-only training on labeled split"
    )
    parser.add_argument("--split_file",     required=True,
        help="Path to split JSON (filtered or legacy schema; auto-detected)")
    parser.add_argument("--output_dir",     required=True,
        help="Directory to save checkpoints and results")

    # Path flags — required for legacy schema, auto-derived for filtered
    parser.add_argument("--coco_label_dir", default=None,
        help="Path to YOLO-format train2017 label directory. "
             "REQUIRED for legacy schema. IGNORED for filtered schema "
             "(auto-derived from split's label_dir_train).")
    parser.add_argument("--val_image_dir",  default=None,
        help="Path to val2017 images directory. REQUIRED for legacy "
             "schema. Auto-derived from split for filtered schema; "
             "passing this flag overrides the auto-derived value.")
    parser.add_argument("--val_label_dir",  default=None,
        help="Path to YOLO-format val2017 labels directory. REQUIRED "
             "for legacy schema. Auto-derived from split for filtered.")

    parser.add_argument("--epochs",   type=int,   default=100,
        help="Maximum training epochs (default: 100). "
             "For filtered-schema smoke runs use 30, real runs 150.")
    parser.add_argument("--patience", type=int,   default=50,
        help="Epochs of no inner-val improvement before early stopping "
             "(default: 50). Only effective with inner_val partition.")
    parser.add_argument("--optimizer", default="AdamW",
        choices=["AdamW", "SGD", "Adam"],
        help="Optimizer (default: AdamW). Forced explicitly to avoid "
             "Ultralytics' optimizer=auto silently picking different "
             "optimizers across different epoch budgets.")
    parser.add_argument("--lr0", type=float, default=0.001,
        help="Initial learning rate (default: 0.001 for AdamW). "
             "Use 0.01 with SGD.")
    parser.add_argument("--batch",    type=int,   default=16)
    parser.add_argument("--imgsz",    type=int,   default=640)
    parser.add_argument("--device",   default="0" if torch.cuda.is_available()
                                                else "cpu")
    parser.add_argument("--base_model", default=None,
        help="Base YOLO model. If omitted: yolov8s.yaml for filtered "
             "schema (from-scratch), yolov8m.pt for legacy.")

    # Pretrained: explicit on/off flags
    pre_group = parser.add_mutually_exclusive_group()
    pre_group.add_argument("--pretrained",    dest="pretrained",
        action="store_true", default=None,
        help="Use ImageNet/COCO-pretrained .pt weights")
    pre_group.add_argument("--no_pretrained", dest="pretrained",
        action="store_false",
        help="Train from scratch (no .pt weights). Default for filtered "
             "schema; required when base_model is a .yaml.")

    parser.add_argument("--workers",  type=int,   default=8)

    args = parser.parse_args()

    summary = run_baseline_a(
        split_file     = args.split_file,
        coco_label_dir = args.coco_label_dir,
        val_image_dir  = args.val_image_dir,
        val_label_dir  = args.val_label_dir,
        output_dir     = args.output_dir,
        epochs         = args.epochs,
        patience       = args.patience,
        optimizer      = args.optimizer,
        lr0            = args.lr0,
        batch          = args.batch,
        imgsz          = args.imgsz,
        device         = args.device,
        base_model     = args.base_model,
        pretrained     = args.pretrained,
        workers        = args.workers,
    )

    print()
    print("=" * 50)
    print("Baseline A complete")
    print(f"  schema:   {summary['schema']}")
    print(f"  mAP50:    {summary['map50']:.4f}")
    print(f"  mAP50-95: {summary['map50_95']:.4f}")
    print("=" * 50)